version: '3'
services:
  web:
    env_file: .env
    build: .
    ports:
    - "5000:5000"
    volumes:
    - ./assets:/assets
    depends_on:
      - "redis"
    restart: always
  redis:
    image: "redis:4-alpine"
